apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: default
  labels:
    app: clickhouse
spec:
  ports:
    - port: 9000
      name: native
    - port: 8123
      name: http
  type: ClusterIP
  selector:
    app: clickhouse

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: linode-block-storage-retain
  resources:
    requests:
      storage: 40Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse-statefulset
  namespace: default
  labels:
    app: clickhouse
spec:
  serviceName: "clickhouse"
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: starcitizentools/clickhouse:v1.0.0
          ports:
            - containerPort: 9000
              name: native
            - containerPort: 8123
              name: http
          volumeMounts:
            - name: pv-data
              mountPath: /var/lib/clickhouse
            - name: clickhouse-config-vol
              mountPath: "/etc/clickhouse-server"
              readOnly: true
            - name: clickhouse-backup-config-vol
              mountPath: /etc/clickhouse-backup
          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-keys
                  key: BACKUP_ACCESS_KEY
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-keys
                  key: BACKUP_SECRET_KEY
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc
          volumes:
        - name: clickhouse-config-vol
          configMap:
            name: clickhouse-config
            items:
            - key: "config.xml"
              path: "config.xml"
            - key: "users.xml"
              path: "users.xml"
        - name: clickhouse-backup-config-vol
          configMap:
            name: clickhouse-backup-config
            items:
            - key: "config.yml"
              path: "config.yml"
