apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-daily
spec:
  schedule: "15 7 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-daily
            image: starcitizentools/mediawiki:139-v2.1.1
            envFrom:
            - secretRef:
                name: mediawiki-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/extensions/CirrusSearch/maintenance/UpdateSuggesterIndex.php &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php --quiet --shallow-update &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/disposeOutdatedEntities.php --quiet &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildPropertyStatistics.php --quiet &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildConceptCache.php --quiet --update --create
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-weekly
spec:
  schedule: "0 8 * * 1"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-weekly
            image: starcitizentools/mediawiki:139-v2.1.1
            envFrom:
            - secretRef:
                name: mediawiki-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php --quiet -d 100 &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php --quiet --skip-import
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-monthly
spec:
  schedule: "0 9 1 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-monthly
            image: starcitizentools/mediawiki:139-v2.1.1
            envFrom:
            - secretRef:
                name: mediawiki-keys
            command:
            - /bin/bash
            - -c
            - php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/removeDuplicateEntities.php --quiet 
          restartPolicy: OnFailure