apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
data: 
  config : |
    [mysqld]
    innodb_buffer_pool_size = 960M
    innodb_log_file_size=240M
    innodb_log_buffer_size=24M
    key_buffer_size=364K
    performance_schema=on
    ignore-db-dirs=lost+found