apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  database_url: mariadb-service 

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      name: mariadb-port
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service-temp
spec:
  selector:
    app: mariadb
  ports:
    - nodePort: 32167
      port: 3306
      targetPort: 3306
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-sts
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec: 
      containers:
        - name: mariadb
          image: mariadb:10.11
          ports:
            - containerPort: 3306 
              name: mariadb-port
          resources:
            limits:
              memory: "1.2Gi"
              cpu: "1000m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prd-db-password
                  key: PRD_DB_PASSWORD
            - name: MARIADB_DATABASE
              value: scw_PROD
          volumeMounts:
            - name: mariadb-pv
              mountPath: /var/lib/mysql
            - name: mariadb-config-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mariadb-pv
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
        - name: mariadb-config-volume
          configMap:
            name: mariadb-config
            items:
            - key: config
              path: my.conf
