apiVersion: v1
kind: Service
metadata:
  name: nginx-phpfpm
spec:
  selector:
    app: nginx-phpfpm
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webroot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
  storageClassName: linode-block-storage-retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-phpfpm
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
  selector:
    matchLabels:
      app: nginx-phpfpm
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: nginx-phpfpm
    spec:
      securityContext:
        fsGroup: 33
      volumes:
      - name: webroot
        persistentVolumeClaim:
          claimName: webroot
      - name: s3-config-vol
        configMap:
          name: s3-config
          items:
          - key: ".s3cfg"
            path: ".s3cfg"
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx
        image: nginx:1.23.3
        ports:
         - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: webroot
            mountPath: /var/www/mediawiki
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d

      - name: php
        image: starcitizentools/mediawiki:139-v1.2.1
        ports:
         - containerPort: 9000
        resources:
          requests:
            memory: "128Mi"
            cpu: "750m"
          limits:
            memory: "768Mi"
            cpu: "2"
        volumeMounts:
        - name: webroot
          mountPath: /var/www/mediawiki
        - name: s3-config-vol
          mountPath: /var/www/.s3cfg
          subPath: .s3cfg
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "rsync -vaO --no-p /var/www/provisioning/ /var/www/mediawiki"]
        envFrom:
        - secretRef:
            name: backup-keys
        env:
        - name: CLOUDFLARE_APITOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-apitoken
              key: cloudflare_apitoken
        - name: CLOUDFLARE_ZONEID
          valueFrom:
            secretKeyRef:
              name: cloudflare-zoneid
              key: cloudflare_zoneid
        - name: DISCORD_WEBHOOKURL
          valueFrom:
            secretKeyRef:
              name: discord-webhookurl
              key: discord_webhookurl
        - name: FLICKR_APIKEY
          valueFrom:
            secretKeyRef:
              name: flickr-apikey
              key: flickr_apikey
        - name: HCAPTCHA_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: hcaptcha-secretkey
              key: hcaptcha_secretkey
        - name: HCAPTCHA_SITEKEY
          valueFrom:
            secretKeyRef:
              name: hcaptcha-sitekey
              key: hcaptcha_sitekey
        - name: MEDIAWIKI_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: mediawiki-secretkey
              key: mw_secretkey
        - name: MEDIAWIKI_UPGRADEKEY
          valueFrom:
            secretKeyRef:
              name: mediawiki-upgradekey
              key: mw_upgradekey
        - name: PRD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prd-db-password
              key: db_password
        - name: IMAGES_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: images-keys
              key: IMAGES_ACCESS_KEY
        - name: IMAGES_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: images-keys
              key: IMAGES_SECRET_KEY
    
      - name: jobrunner
        image: starcitizentools/mediawiki:jobrunner-v1.0.0
        command: ["/bin/sh"]
        args: ["-c", "/var/www/html/mediawiki-services-jobrunner/entrypoint.sh"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        volumeMounts:
          - name: webroot
            mountPath: /var/www/mediawiki
        env:
        - name: CLOUDFLARE_APITOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-apitoken
              key: cloudflare_apitoken
        - name: CLOUDFLARE_ZONEID
          valueFrom:
            secretKeyRef:
              name: cloudflare-zoneid
              key: cloudflare_zoneid
        - name: DISCORD_WEBHOOKURL
          valueFrom:
            secretKeyRef:
              name: discord-webhookurl
              key: discord_webhookurl
        - name: FLICKR_APIKEY
          valueFrom:
            secretKeyRef:
              name: flickr-apikey
              key: flickr_apikey
        - name: HCAPTCHA_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: hcaptcha-secretkey
              key: hcaptcha_secretkey
        - name: HCAPTCHA_SITEKEY
          valueFrom:
            secretKeyRef:
              name: hcaptcha-sitekey
              key: hcaptcha_sitekey
        - name: MEDIAWIKI_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: mediawiki-secretkey
              key: mw_secretkey
        - name: MEDIAWIKI_UPGRADEKEY
          valueFrom:
            secretKeyRef:
              name: mediawiki-upgradekey
              key: mw_upgradekey
        - name: PRD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prd-db-password
              key: db_password
        - name: IMAGES_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: images-keys
              key: IMAGES_ACCESS_KEY
        - name: IMAGES_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: images-keys
              key: IMAGES_SECRET_KEY

      - name: jobchron
        image: starcitizentools/mediawiki:jobrunner-v1.0.0
        command: ["/bin/sh"]
        args: ["-c", "/var/www/html/mediawiki-services-jobrunner/entrypoint.sh"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        volumeMounts:
          - name: webroot
            mountPath: /var/www/mediawiki
        env:
        - name: PRD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prd-db-password
              key: db_password
        - name: RUNNER_TYPE
          value: Chron
