apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mw-daily
spec:
  schedule: "15 7 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-mw-daily
            image: starcitizentools/mediawiki:smw-24.10.23.468
            envFrom:
            - secretRef:
                name: mediawiki-keys
            - secretRef:
                name: prd-db-password
            - secretRef:
                name: images-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/maintenance/initSiteStats.php --update &&
                php /var/www/mediawiki/extensions/CirrusSearch/maintenance/UpdateSuggesterIndex.php &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php --shallow-update &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/disposeOutdatedEntities.php &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildPropertyStatistics.php &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildConceptCache.php --update --create
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mw-tridaily
spec:
  schedule: "15 4 */3 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-mw-tridaily
            image: starcitizentools/mediawiki:smw-24.10.23.468
            envFrom:
            - secretRef:
                name: mediawiki-keys
            - secretRef:
                name: prd-db-password
            - secretRef:
                name: images-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/maintenance/updateSpecialPages.php
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mw-biweekly
spec:
  schedule: "0 8 1,15 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-mw-biweekly
            image: starcitizentools/mediawiki:smw-24.10.23.468
            envFrom:
            - secretRef:
                name: mediawiki-keys
            - secretRef:
                name: prd-db-password
            - secretRef:
                name: images-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/maintenance/initSiteStats.php --update --active &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/rebuildData.php  -d 100 &&
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php --skip-import
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mw-monthly
spec:
  schedule: "0 9 1 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-mw-monthly
            image: starcitizentools/mediawiki:smw-24.10.23.468
            envFrom:
            - secretRef:
                name: mediawiki-keys
            - secretRef:
                name: prd-db-password
            - secretRef:
                name: images-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/maintenance/cleanupUploadStash.php
                php /var/www/mediawiki/maintenance/cleanupWatchlist.php --fix
                php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/removeDuplicateEntities.php
          restartPolicy: OnFailure
