apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mw-daily
spec:
  schedule: "15 7 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-mw-daily
            image: starcitizentools/mediawiki:smw-26.03.01.473
            envFrom:
            - secretRef:
                name: mediawiki-keys
            - secretRef:
                name: prd-db-password
            - secretRef:
                name: images-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/maintenance/run.php initSiteStats.php --update &&
                php /var/www/mediawiki/maintenance/run.php CirrusSearch:UpdateSuggesterIndex &&
                php /var/www/mediawiki/maintenance/run.php SemanticMediaWiki:rebuildData --shallow-update &&
                php /var/www/mediawiki/maintenance/run.php SemanticMediaWiki:disposeOutdatedEntities &&
                php /var/www/mediawiki/maintenance/run.php SemanticMediaWiki:rebuildPropertyStatistics &&
                php /var/www/mediawiki/maintenance/run.php SemanticMediaWiki:rebuildConceptCache --update --create
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mw-tridaily
spec:
  schedule: "15 4 */3 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-mw-tridaily
            image: starcitizentools/mediawiki:smw-26.03.01.473
            envFrom:
            - secretRef:
                name: mediawiki-keys
            - secretRef:
                name: prd-db-password
            - secretRef:
                name: images-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/maintenance/run.php updateSpecialPages
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mw-biweekly
spec:
  schedule: "0 8 1,15 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-mw-biweekly
            image: starcitizentools/mediawiki:smw-26.03.01.473
            envFrom:
            - secretRef:
                name: mediawiki-keys
            - secretRef:
                name: prd-db-password
            - secretRef:
                name: images-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/maintenance/run.php updateSpecialPages --override --only=Ancientpages &&
                php /var/www/mediawiki/maintenance/run.php updateSpecialPages --override --only=Deadendpages &&
                php /var/www/mediawiki/maintenance/run.php updateSpecialPages --override --only=Fewestrevisions &&
                php /var/www/mediawiki/maintenance/run.php updateSpecialPages --override --only=Mostlinked &&
                php /var/www/mediawiki/maintenance/run.php updateSpecialPages --override --only=Mostrevisions &&
                php /var/www/mediawiki/maintenance/run.php updateSpecialPages --override --only=Wantedpages &&
                php /var/www/mediawiki/maintenance/run.php initSiteStats --update --active &&
                php /var/www/mediawiki/maintenance/run.php SemanticMediaWiki:rebuildData -d 100 &&
                php /var/www/mediawiki/maintenance/run.php SemanticMediaWiki:setupStore --skip-import
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-mw-monthly
spec:
  schedule: "0 9 1 * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob-mw-monthly
            image: starcitizentools/mediawiki:smw-26.03.01.473
            envFrom:
            - secretRef:
                name: mediawiki-keys
            - secretRef:
                name: prd-db-password
            - secretRef:
                name: images-keys
            command: ["/bin/sh"]
            args:
            - -c
            - >-
                php /var/www/mediawiki/maintenance/run.php cleanupUploadStash &&
                php /var/www/mediawiki/maintenance/run.php cleanupWatchlist --fix &&
                php /var/www/mediawiki/maintenance/run.php refreshLinks --dfn-only &&
                php /var/www/mediawiki/maintenance/run.php SemanticMediaWiki:removeDuplicateEntities
          restartPolicy: OnFailure
