apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
  selector:
    matchLabels:
      app: nginx
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      securityContext:
        fsGroup: 33
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
          items:
          - key: config
            path: site.conf
      containers:
      - name: nginx
        image: starcitizentools/nginx:v0.0.3
        ports:
         - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d
