apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-mediawiki-jobs
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
  selector:
    matchLabels:
      app: php-mediawiki-jobs
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: php-mediawiki-jobs
    spec:
      securityContext:
        fsGroup: 33
      containers:
      - name: jobrunner
        image: starcitizentools/mediawiki:smw-jobrunner-v1.0.0
        command: ["/bin/sh"]
        args: ["-c", "/var/www/html/mediawiki-services-jobrunner/entrypoint.sh"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        envFrom:
        - secretRef:
            name: mediawiki-keys
        - secretRef:
            name: images-keys

      - name: jobchron
        image: starcitizentools/mediawiki:smw-jobrunner-v1.0.0
        command: ["/bin/sh"]
        args: ["-c", "/var/www/html/mediawiki-services-jobrunner/entrypoint.sh"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        envFrom:
        - secretRef:
            name: mediawiki-keys
        - name: RUNNER_TYPE
          value: Chron
