apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl-exec

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exec-pods
rules:
  - apiGroups: [""]
    resources:
      - pods/exec
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-pods-to-sa
subjects:
  - kind: ServiceAccount
    name: internal-kubectl-exec
roleRef:
  kind: Role
  name: exec-pods
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-mediawiki-jobs
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
  selector:
    matchLabels:
      app: php-mediawiki-jobs
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: php-mediawiki-jobs
    spec:
      serviceAccountName: internal-kubectl-exec
      securityContext:
        fsGroup: 33
      containers:
      - name: jobrunner
        image: starcitizentools/mediawiki:smw-jobrunner-v1.0.0
        command: ["/bin/sh"]
        args: ["-c", "/var/www/html/mediawiki-services-jobrunner/entrypoint.sh"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        envFrom:
        - secretRef:
            name: mediawiki-keys
        - secretRef:
            name: images-keys
        volumeMounts:
        - name: smw
          mountPath: /usr/local/smw
      - name: jobchron
        image: starcitizentools/mediawiki:smw-jobrunner-v1.0.0
        command: ["/bin/sh"]
        args: ["-c", "/var/www/html/mediawiki-services-jobrunner/entrypoint.sh"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        envFrom:
        - secretRef:
            name: mediawiki-keys
        env:
        - name: RUNNER_TYPE
          value: Chron
      initContainers:
      - name: smw-setup-file
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - kubectl cp php-mediawiki:/var/www/mediawiki/extenions/SemanticMediawiki/.smw.json /usr/local/smw/.smw.json
        volumeMounts:
          - name: smw
            mountPath:  /usr/local/smw
      volumes:
      - name: smw
        emptyDir: {}