apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php-mediawiki
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-mediawiki
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
  selector:
    matchLabels:
      app: php-mediawiki
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: php-mediawiki
    spec:
      securityContext:
        fsGroup: 33
      containers:
      - name: php-mediawiki
        image: starcitizentools/mediawiki:smw-v0.0.1
        ports:
         - containerPort: 9000
        resources:
          requests:
            memory: "128Mi"
            cpu: "750m"
          limits:
            memory: "768Mi"
            cpu: "2"
        envFrom:
        - secretRef:
            name: backup-keys
        env:
        - name: CLOUDFLARE_APITOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-apitoken
              key: cloudflare_apitoken
        - name: CLOUDFLARE_ZONEID
          valueFrom:
            secretKeyRef:
              name: cloudflare-zoneid
              key: cloudflare_zoneid
        - name: DISCORD_WEBHOOKURL
          valueFrom:
            secretKeyRef:
              name: discord-webhookurl
              key: discord_webhookurl
        - name: FLICKR_APIKEY
          valueFrom:
            secretKeyRef:
              name: flickr-apikey
              key: flickr_apikey
        - name: HCAPTCHA_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: hcaptcha-secretkey
              key: hcaptcha_secretkey
        - name: HCAPTCHA_SITEKEY
          valueFrom:
            secretKeyRef:
              name: hcaptcha-sitekey
              key: hcaptcha_sitekey
        - name: MEDIAWIKI_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: mediawiki-secretkey
              key: mw_secretkey
        - name: MEDIAWIKI_UPGRADEKEY
          valueFrom:
            secretKeyRef:
              name: mediawiki-upgradekey
              key: mw_upgradekey
        - name: PRD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: prd-db-password
              key: db_password
        - name: IMAGES_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: images-keys
              key: IMAGES_ACCESS_KEY
        - name: IMAGES_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: images-keys
              key: IMAGES_SECRET_KEY