apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: php-mediawiki
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9000
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-mediawiki
spec:
  strategy:
    rollingUpdate:
      maxSurge: 100%
  selector:
    matchLabels:
      app: php-mediawiki
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: php-mediawiki
    spec:
      securityContext:
        fsGroup: 33
      containers:
      - name: php-mediawiki
        image: starcitizentools/mediawiki:smw-24.09.28.419
        ports:
         - containerPort: 9000
        resources:
          requests:
            memory: "64Mi"
            cpu: "350m"
          limits:
            memory: "1.5Gi"
            cpu: "4"
        envFrom:
        - secretRef:
            name: mediawiki-keys
        - secretRef:
            name: images-keys
        - secretRef:
            name: prd-db-password
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "php /var/www/mediawiki/extensions/SemanticMediaWiki/maintenance/setupStore.php --quiet"]
