apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      name: redis-port
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: linode-block-storage-retain

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
spec:
  serviceName: redis-service
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: starcitizentools/redis:23.11.06.3
          ports:
            - containerPort: 6379
              name: redis
          resources:
            limits:
              memory: "3Gi"
              cpu: "1"
          volumeMounts:
            - name: redis-pv
              mountPath: /data
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pvc
