apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
data:
  allow-snippet-annotations: "true"
  ssl-buffer-size: "16K"
  use-gzip: "false"
  enable-brotli: "false"
  use-proxy-protocol: "true"
  use-forwarded-headers: "true"
  worker-processes: "1"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: nginx-ingress
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "64M"
    nginx.ingress.kubernetes.io/configuration-snippet: |
          more_set_headers "X-Forwarded-For $http_x_forwarded_for";

spec:
  ingressClassName: nginx
  rules:
    - host: analytics.starcitizen.tools   # your custom dns address (e.g. plausible.example.com)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plausible
                port:
                  number: 8000
    - host: starcitizen.tools
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-phpfpm
                port:
                  number: 80
    - host: scw.czen.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-phpfpm
                port:
                  number: 80
  tls:
    - hosts:
        - analytics.starcitizen.tools      # your custom dns address (again, same as above)
      secretName: plausible-ingress-cert
    - hosts:
        - starcitizen.tools
      secretName: mediawiki-ingress-cert
    - hosts:
        - www.starcitizen.tools
      secretName: www-mediawiki-ingress-cert
    - hosts:
        - scw.czen.me
      secretName: czen-mediawiki-ingress-cert