apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
data:
  worker-processes: "1"
  allow-snippet-annotations: "true"
  ssl-buffer-size: "16K"
  use-gzip: "false"
  enable-brotli: "true"
  ssl-redirect: "false"
  backend-protocol: "HTTP"
  enable-cors: "true"
  enable-ocsp: "true"
  proxy-body-size: "64M"
  
  use-proxy-protocol: "true"
  server-snippet: |
    real_ip_header CF-Connecting-IP;
    set_real_ip_from 194.195.247.0/24;
    set_real_ip_from 103.21.244.0/22;
    set_real_ip_from 103.22.200.0/22;
    set_real_ip_from 103.31.4.0/22;
    set_real_ip_from 104.16.0.0/12;
    set_real_ip_from 104.24.0.0/14;
    set_real_ip_from 108.162.192.0/18;
    set_real_ip_from 131.0.72.0/22;
    set_real_ip_from 141.101.64.0/18;
    set_real_ip_from 162.158.0.0/15;
    set_real_ip_from 172.64.0.0/13;
    set_real_ip_from 173.245.48.0/20;
    set_real_ip_from 188.114.96.0/20;
    set_real_ip_from 190.93.240.0/20;
    set_real_ip_from 197.234.240.0/22;
    set_real_ip_from 198.41.128.0/17;
    set_real_ip_from 2400:cb00::/32;
    set_real_ip_from 2606:4700::/32;
    set_real_ip_from 2803:f800::/32;
    set_real_ip_from 2405:b500::/32;
    set_real_ip_from 2405:8100::/32;
    set_real_ip_from 2c0f:f248::/32;
    set_real_ip_from 2a06:98c0::/29;

  hsts-max-age: "63072000"
  hsts-preload: "true"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: nginx-ingress
  annotations:
  
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Ban very old versions of Chrome. For now we're banning up to Chrome 125.
      if ($http_user_agent ~* "Chrome/[0-9]{1,2}\.") { return 403; }
      if ($http_user_agent ~* "Chrome/(10[0-9]|11[0-9]|12[0-5])\.") { return 403; }
      # Ban very old versions of Firefox. For now we're banning up to Firefox 100.
      if ($http_user_agent ~* "Firefox/[0-9]{1,2}\.") { return 403; }
      if ($http_user_agent ~* "Firefox/100\.") { return 403; }
      # Ban very old versions of Windows. For now we're banning up to Windows 7.
      if ($http_user_agent ~* "Windows NT [0-5]\.") { return 403; }
      if ($http_user_agent ~* "Windows NT 6\.[01]") { return 403; }
      # Ban very old versions of Mac OS X. For now we're banning up to Mac OS X 10.6.
      if ($http_user_agent ~* "Mac OS X 10\.[0-6]") { return 403; }
spec:
  ingressClassName: nginx
  rules:
    - host: analytics.starcitizen.tools
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plausible
                port:
                  number: 8000
    - host: starcitizen.tools
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
    - host: scw.czen.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
  tls:
    - hosts:
        - analytics.starcitizen.tools
      secretName: plausible-ingress-cert
    - hosts:
        - starcitizen.tools
      secretName: mediawiki-ingress-cert
    - hosts:
        - www.starcitizen.tools
      secretName: www-mediawiki-ingress-cert
    - hosts:
        - scw.czen.me
      secretName: czen-mediawiki-ingress-cert
