name: Mediawiki Kubernetes Cluster Deployment

on:
  push:
    branches:
      - 'smw'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v3
        id: install

      - uses: actions/checkout@v3
      
      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v3.0
        with:
          cluster-type: generic
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG_DEV }}

      - name: MEDIAWIKI Secrets
        uses: Azure/k8s-create-secret@v4.0
        with:
          secret-type: 'generic'
          secret-name: mediawiki-keys
          data: ${{ secrets.MEDIAWIKI_KEYS }}

      - name: PLAUSIBLE_POSTGRES Secret
        uses: Azure/k8s-create-secret@v4.0
        with:
          secret-type: 'generic'
          secret-name: plausible-postgres
          data: ${{ secrets.PLAUSIBLE_POSTGRES }}

      - name: PLAUSIBLE_CONFIG Secret
        uses: Azure/k8s-create-secret@v4.0
        with:
          secret-type: 'generic'
          secret-name: plausible-config
          data: ${{ secrets.PLAUSIBLE_CONFIG }}
      
      - name: BACKUP_KEYS Secret
        uses: Azure/k8s-create-secret@v4.0
        with:
          secret-type: 'generic'
          secret-name: backup-keys
          data: ${{ secrets.BACKUP_KEYS }}

      - name: IMAGES_KEYS Secret
        uses: Azure/k8s-create-secret@v4.0
        with:
          secret-type: 'generic'
          secret-name: images-keys
          data: ${{ secrets.IMAGES_READ_KEYS }}

      - name: SITEMAP_KEYS Secret
        uses: Azure/k8s-create-secret@v4.0
        with:
          secret-type: 'generic'
          secret-name: sitemap-keys
          data: ${{ secrets.SITEMAP_KEYS }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          # Path to the manifest files which will be used for deployment.
          manifests: |
            mediawiki
            shared
          strategy: basic
          action: deploy
